// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft_rpc.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_raft_5frpc_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_raft_5frpc_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_raft_5frpc_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_raft_5frpc_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_raft_5frpc_2eproto;
namespace raftrpc {
class AppendEntriesArgs;
struct AppendEntriesArgsDefaultTypeInternal;
extern AppendEntriesArgsDefaultTypeInternal _AppendEntriesArgs_default_instance_;
class AppendEntriesReply;
struct AppendEntriesReplyDefaultTypeInternal;
extern AppendEntriesReplyDefaultTypeInternal _AppendEntriesReply_default_instance_;
class InstallSnapshotArgs;
struct InstallSnapshotArgsDefaultTypeInternal;
extern InstallSnapshotArgsDefaultTypeInternal _InstallSnapshotArgs_default_instance_;
class InstallSnapshotReply;
struct InstallSnapshotReplyDefaultTypeInternal;
extern InstallSnapshotReplyDefaultTypeInternal _InstallSnapshotReply_default_instance_;
class LogEntry;
struct LogEntryDefaultTypeInternal;
extern LogEntryDefaultTypeInternal _LogEntry_default_instance_;
class RequestVoteArgs;
struct RequestVoteArgsDefaultTypeInternal;
extern RequestVoteArgsDefaultTypeInternal _RequestVoteArgs_default_instance_;
class RequestVoteReply;
struct RequestVoteReplyDefaultTypeInternal;
extern RequestVoteReplyDefaultTypeInternal _RequestVoteReply_default_instance_;
}  // namespace raftrpc
PROTOBUF_NAMESPACE_OPEN
template<> ::raftrpc::AppendEntriesArgs* Arena::CreateMaybeMessage<::raftrpc::AppendEntriesArgs>(Arena*);
template<> ::raftrpc::AppendEntriesReply* Arena::CreateMaybeMessage<::raftrpc::AppendEntriesReply>(Arena*);
template<> ::raftrpc::InstallSnapshotArgs* Arena::CreateMaybeMessage<::raftrpc::InstallSnapshotArgs>(Arena*);
template<> ::raftrpc::InstallSnapshotReply* Arena::CreateMaybeMessage<::raftrpc::InstallSnapshotReply>(Arena*);
template<> ::raftrpc::LogEntry* Arena::CreateMaybeMessage<::raftrpc::LogEntry>(Arena*);
template<> ::raftrpc::RequestVoteArgs* Arena::CreateMaybeMessage<::raftrpc::RequestVoteArgs>(Arena*);
template<> ::raftrpc::RequestVoteReply* Arena::CreateMaybeMessage<::raftrpc::RequestVoteReply>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace raftrpc {

// ===================================================================

class LogEntry final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:raftrpc.LogEntry) */ {
 public:
  inline LogEntry() : LogEntry(nullptr) {}
  ~LogEntry() override;
  explicit PROTOBUF_CONSTEXPR LogEntry(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LogEntry(const LogEntry& from);
  LogEntry(LogEntry&& from) noexcept
    : LogEntry() {
    *this = ::std::move(from);
  }

  inline LogEntry& operator=(const LogEntry& from) {
    CopyFrom(from);
    return *this;
  }
  inline LogEntry& operator=(LogEntry&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LogEntry& default_instance() {
    return *internal_default_instance();
  }
  static inline const LogEntry* internal_default_instance() {
    return reinterpret_cast<const LogEntry*>(
               &_LogEntry_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(LogEntry& a, LogEntry& b) {
    a.Swap(&b);
  }
  inline void Swap(LogEntry* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LogEntry* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LogEntry* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LogEntry>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LogEntry& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LogEntry& from) {
    LogEntry::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LogEntry* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "raftrpc.LogEntry";
  }
  protected:
  explicit LogEntry(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCommandFieldNumber = 1,
    kLogTermFieldNumber = 2,
    kLogIndexFieldNumber = 3,
  };
  // bytes command = 1;
  void clear_command();
  const std::string& command() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_command(ArgT0&& arg0, ArgT... args);
  std::string* mutable_command();
  PROTOBUF_NODISCARD std::string* release_command();
  void set_allocated_command(std::string* command);
  private:
  const std::string& _internal_command() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_command(const std::string& value);
  std::string* _internal_mutable_command();
  public:

  // int32 log_term = 2;
  void clear_log_term();
  int32_t log_term() const;
  void set_log_term(int32_t value);
  private:
  int32_t _internal_log_term() const;
  void _internal_set_log_term(int32_t value);
  public:

  // int32 log_index = 3;
  void clear_log_index();
  int32_t log_index() const;
  void set_log_index(int32_t value);
  private:
  int32_t _internal_log_index() const;
  void _internal_set_log_index(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:raftrpc.LogEntry)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr command_;
    int32_t log_term_;
    int32_t log_index_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_raft_5frpc_2eproto;
};
// -------------------------------------------------------------------

class AppendEntriesArgs final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:raftrpc.AppendEntriesArgs) */ {
 public:
  inline AppendEntriesArgs() : AppendEntriesArgs(nullptr) {}
  ~AppendEntriesArgs() override;
  explicit PROTOBUF_CONSTEXPR AppendEntriesArgs(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AppendEntriesArgs(const AppendEntriesArgs& from);
  AppendEntriesArgs(AppendEntriesArgs&& from) noexcept
    : AppendEntriesArgs() {
    *this = ::std::move(from);
  }

  inline AppendEntriesArgs& operator=(const AppendEntriesArgs& from) {
    CopyFrom(from);
    return *this;
  }
  inline AppendEntriesArgs& operator=(AppendEntriesArgs&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AppendEntriesArgs& default_instance() {
    return *internal_default_instance();
  }
  static inline const AppendEntriesArgs* internal_default_instance() {
    return reinterpret_cast<const AppendEntriesArgs*>(
               &_AppendEntriesArgs_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(AppendEntriesArgs& a, AppendEntriesArgs& b) {
    a.Swap(&b);
  }
  inline void Swap(AppendEntriesArgs* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AppendEntriesArgs* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AppendEntriesArgs* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AppendEntriesArgs>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AppendEntriesArgs& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AppendEntriesArgs& from) {
    AppendEntriesArgs::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AppendEntriesArgs* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "raftrpc.AppendEntriesArgs";
  }
  protected:
  explicit AppendEntriesArgs(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLogEntriesFieldNumber = 6,
    kTermFieldNumber = 1,
    kLeaderIdFieldNumber = 2,
    kLeaderCommitFieldNumber = 3,
    kPrevLogTermFieldNumber = 4,
    kPrevLogIndexFieldNumber = 5,
  };
  // repeated .raftrpc.LogEntry log_entries = 6;
  int log_entries_size() const;
  private:
  int _internal_log_entries_size() const;
  public:
  void clear_log_entries();
  ::raftrpc::LogEntry* mutable_log_entries(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::raftrpc::LogEntry >*
      mutable_log_entries();
  private:
  const ::raftrpc::LogEntry& _internal_log_entries(int index) const;
  ::raftrpc::LogEntry* _internal_add_log_entries();
  public:
  const ::raftrpc::LogEntry& log_entries(int index) const;
  ::raftrpc::LogEntry* add_log_entries();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::raftrpc::LogEntry >&
      log_entries() const;

  // int32 term = 1;
  void clear_term();
  int32_t term() const;
  void set_term(int32_t value);
  private:
  int32_t _internal_term() const;
  void _internal_set_term(int32_t value);
  public:

  // int32 leader_id = 2;
  void clear_leader_id();
  int32_t leader_id() const;
  void set_leader_id(int32_t value);
  private:
  int32_t _internal_leader_id() const;
  void _internal_set_leader_id(int32_t value);
  public:

  // int32 leader_commit = 3;
  void clear_leader_commit();
  int32_t leader_commit() const;
  void set_leader_commit(int32_t value);
  private:
  int32_t _internal_leader_commit() const;
  void _internal_set_leader_commit(int32_t value);
  public:

  // int32 prev_log_term = 4;
  void clear_prev_log_term();
  int32_t prev_log_term() const;
  void set_prev_log_term(int32_t value);
  private:
  int32_t _internal_prev_log_term() const;
  void _internal_set_prev_log_term(int32_t value);
  public:

  // int32 prev_log_index = 5;
  void clear_prev_log_index();
  int32_t prev_log_index() const;
  void set_prev_log_index(int32_t value);
  private:
  int32_t _internal_prev_log_index() const;
  void _internal_set_prev_log_index(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:raftrpc.AppendEntriesArgs)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::raftrpc::LogEntry > log_entries_;
    int32_t term_;
    int32_t leader_id_;
    int32_t leader_commit_;
    int32_t prev_log_term_;
    int32_t prev_log_index_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_raft_5frpc_2eproto;
};
// -------------------------------------------------------------------

class AppendEntriesReply final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:raftrpc.AppendEntriesReply) */ {
 public:
  inline AppendEntriesReply() : AppendEntriesReply(nullptr) {}
  ~AppendEntriesReply() override;
  explicit PROTOBUF_CONSTEXPR AppendEntriesReply(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AppendEntriesReply(const AppendEntriesReply& from);
  AppendEntriesReply(AppendEntriesReply&& from) noexcept
    : AppendEntriesReply() {
    *this = ::std::move(from);
  }

  inline AppendEntriesReply& operator=(const AppendEntriesReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline AppendEntriesReply& operator=(AppendEntriesReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AppendEntriesReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const AppendEntriesReply* internal_default_instance() {
    return reinterpret_cast<const AppendEntriesReply*>(
               &_AppendEntriesReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(AppendEntriesReply& a, AppendEntriesReply& b) {
    a.Swap(&b);
  }
  inline void Swap(AppendEntriesReply* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AppendEntriesReply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AppendEntriesReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AppendEntriesReply>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AppendEntriesReply& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AppendEntriesReply& from) {
    AppendEntriesReply::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AppendEntriesReply* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "raftrpc.AppendEntriesReply";
  }
  protected:
  explicit AppendEntriesReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTermFieldNumber = 1,
    kSuccessFieldNumber = 2,
    kNextUpdateIndexFieldNumber = 3,
    kRaftStateFieldNumber = 4,
  };
  // int32 term = 1;
  void clear_term();
  int32_t term() const;
  void set_term(int32_t value);
  private:
  int32_t _internal_term() const;
  void _internal_set_term(int32_t value);
  public:

  // bool success = 2;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // int32 next_update_index = 3;
  void clear_next_update_index();
  int32_t next_update_index() const;
  void set_next_update_index(int32_t value);
  private:
  int32_t _internal_next_update_index() const;
  void _internal_set_next_update_index(int32_t value);
  public:

  // int32 raft_state = 4;
  void clear_raft_state();
  int32_t raft_state() const;
  void set_raft_state(int32_t value);
  private:
  int32_t _internal_raft_state() const;
  void _internal_set_raft_state(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:raftrpc.AppendEntriesReply)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t term_;
    bool success_;
    int32_t next_update_index_;
    int32_t raft_state_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_raft_5frpc_2eproto;
};
// -------------------------------------------------------------------

class RequestVoteArgs final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:raftrpc.RequestVoteArgs) */ {
 public:
  inline RequestVoteArgs() : RequestVoteArgs(nullptr) {}
  ~RequestVoteArgs() override;
  explicit PROTOBUF_CONSTEXPR RequestVoteArgs(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RequestVoteArgs(const RequestVoteArgs& from);
  RequestVoteArgs(RequestVoteArgs&& from) noexcept
    : RequestVoteArgs() {
    *this = ::std::move(from);
  }

  inline RequestVoteArgs& operator=(const RequestVoteArgs& from) {
    CopyFrom(from);
    return *this;
  }
  inline RequestVoteArgs& operator=(RequestVoteArgs&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RequestVoteArgs& default_instance() {
    return *internal_default_instance();
  }
  static inline const RequestVoteArgs* internal_default_instance() {
    return reinterpret_cast<const RequestVoteArgs*>(
               &_RequestVoteArgs_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(RequestVoteArgs& a, RequestVoteArgs& b) {
    a.Swap(&b);
  }
  inline void Swap(RequestVoteArgs* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RequestVoteArgs* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RequestVoteArgs* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RequestVoteArgs>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RequestVoteArgs& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RequestVoteArgs& from) {
    RequestVoteArgs::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RequestVoteArgs* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "raftrpc.RequestVoteArgs";
  }
  protected:
  explicit RequestVoteArgs(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTermFieldNumber = 1,
    kCandidateIdFieldNumber = 2,
    kLastLogTermFieldNumber = 3,
    kLastLogIndexFieldNumber = 4,
  };
  // int32 term = 1;
  void clear_term();
  int32_t term() const;
  void set_term(int32_t value);
  private:
  int32_t _internal_term() const;
  void _internal_set_term(int32_t value);
  public:

  // int32 candidate_id = 2;
  void clear_candidate_id();
  int32_t candidate_id() const;
  void set_candidate_id(int32_t value);
  private:
  int32_t _internal_candidate_id() const;
  void _internal_set_candidate_id(int32_t value);
  public:

  // int32 last_log_term = 3;
  void clear_last_log_term();
  int32_t last_log_term() const;
  void set_last_log_term(int32_t value);
  private:
  int32_t _internal_last_log_term() const;
  void _internal_set_last_log_term(int32_t value);
  public:

  // int32 last_log_index = 4;
  void clear_last_log_index();
  int32_t last_log_index() const;
  void set_last_log_index(int32_t value);
  private:
  int32_t _internal_last_log_index() const;
  void _internal_set_last_log_index(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:raftrpc.RequestVoteArgs)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t term_;
    int32_t candidate_id_;
    int32_t last_log_term_;
    int32_t last_log_index_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_raft_5frpc_2eproto;
};
// -------------------------------------------------------------------

class RequestVoteReply final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:raftrpc.RequestVoteReply) */ {
 public:
  inline RequestVoteReply() : RequestVoteReply(nullptr) {}
  ~RequestVoteReply() override;
  explicit PROTOBUF_CONSTEXPR RequestVoteReply(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RequestVoteReply(const RequestVoteReply& from);
  RequestVoteReply(RequestVoteReply&& from) noexcept
    : RequestVoteReply() {
    *this = ::std::move(from);
  }

  inline RequestVoteReply& operator=(const RequestVoteReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline RequestVoteReply& operator=(RequestVoteReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RequestVoteReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const RequestVoteReply* internal_default_instance() {
    return reinterpret_cast<const RequestVoteReply*>(
               &_RequestVoteReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(RequestVoteReply& a, RequestVoteReply& b) {
    a.Swap(&b);
  }
  inline void Swap(RequestVoteReply* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RequestVoteReply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RequestVoteReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RequestVoteReply>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RequestVoteReply& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RequestVoteReply& from) {
    RequestVoteReply::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RequestVoteReply* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "raftrpc.RequestVoteReply";
  }
  protected:
  explicit RequestVoteReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTermFieldNumber = 1,
    kVoteGrantedFieldNumber = 2,
    kVoteStateFieldNumber = 3,
  };
  // int32 term = 1;
  void clear_term();
  int32_t term() const;
  void set_term(int32_t value);
  private:
  int32_t _internal_term() const;
  void _internal_set_term(int32_t value);
  public:

  // bool vote_granted = 2;
  void clear_vote_granted();
  bool vote_granted() const;
  void set_vote_granted(bool value);
  private:
  bool _internal_vote_granted() const;
  void _internal_set_vote_granted(bool value);
  public:

  // int32 vote_state = 3;
  void clear_vote_state();
  int32_t vote_state() const;
  void set_vote_state(int32_t value);
  private:
  int32_t _internal_vote_state() const;
  void _internal_set_vote_state(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:raftrpc.RequestVoteReply)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t term_;
    bool vote_granted_;
    int32_t vote_state_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_raft_5frpc_2eproto;
};
// -------------------------------------------------------------------

class InstallSnapshotArgs final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:raftrpc.InstallSnapshotArgs) */ {
 public:
  inline InstallSnapshotArgs() : InstallSnapshotArgs(nullptr) {}
  ~InstallSnapshotArgs() override;
  explicit PROTOBUF_CONSTEXPR InstallSnapshotArgs(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  InstallSnapshotArgs(const InstallSnapshotArgs& from);
  InstallSnapshotArgs(InstallSnapshotArgs&& from) noexcept
    : InstallSnapshotArgs() {
    *this = ::std::move(from);
  }

  inline InstallSnapshotArgs& operator=(const InstallSnapshotArgs& from) {
    CopyFrom(from);
    return *this;
  }
  inline InstallSnapshotArgs& operator=(InstallSnapshotArgs&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InstallSnapshotArgs& default_instance() {
    return *internal_default_instance();
  }
  static inline const InstallSnapshotArgs* internal_default_instance() {
    return reinterpret_cast<const InstallSnapshotArgs*>(
               &_InstallSnapshotArgs_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(InstallSnapshotArgs& a, InstallSnapshotArgs& b) {
    a.Swap(&b);
  }
  inline void Swap(InstallSnapshotArgs* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InstallSnapshotArgs* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InstallSnapshotArgs* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<InstallSnapshotArgs>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const InstallSnapshotArgs& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const InstallSnapshotArgs& from) {
    InstallSnapshotArgs::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InstallSnapshotArgs* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "raftrpc.InstallSnapshotArgs";
  }
  protected:
  explicit InstallSnapshotArgs(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 5,
    kTermFieldNumber = 1,
    kLeaderIdFieldNumber = 2,
    kLastSnapshotTermFieldNumber = 3,
    kLastSnapshotIndexFieldNumber = 4,
  };
  // bytes data = 5;
  void clear_data();
  const std::string& data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // int32 term = 1;
  void clear_term();
  int32_t term() const;
  void set_term(int32_t value);
  private:
  int32_t _internal_term() const;
  void _internal_set_term(int32_t value);
  public:

  // int32 leader_id = 2;
  void clear_leader_id();
  int32_t leader_id() const;
  void set_leader_id(int32_t value);
  private:
  int32_t _internal_leader_id() const;
  void _internal_set_leader_id(int32_t value);
  public:

  // int32 last_snapshot_term = 3;
  void clear_last_snapshot_term();
  int32_t last_snapshot_term() const;
  void set_last_snapshot_term(int32_t value);
  private:
  int32_t _internal_last_snapshot_term() const;
  void _internal_set_last_snapshot_term(int32_t value);
  public:

  // int32 last_snapshot_index = 4;
  void clear_last_snapshot_index();
  int32_t last_snapshot_index() const;
  void set_last_snapshot_index(int32_t value);
  private:
  int32_t _internal_last_snapshot_index() const;
  void _internal_set_last_snapshot_index(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:raftrpc.InstallSnapshotArgs)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
    int32_t term_;
    int32_t leader_id_;
    int32_t last_snapshot_term_;
    int32_t last_snapshot_index_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_raft_5frpc_2eproto;
};
// -------------------------------------------------------------------

class InstallSnapshotReply final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:raftrpc.InstallSnapshotReply) */ {
 public:
  inline InstallSnapshotReply() : InstallSnapshotReply(nullptr) {}
  ~InstallSnapshotReply() override;
  explicit PROTOBUF_CONSTEXPR InstallSnapshotReply(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  InstallSnapshotReply(const InstallSnapshotReply& from);
  InstallSnapshotReply(InstallSnapshotReply&& from) noexcept
    : InstallSnapshotReply() {
    *this = ::std::move(from);
  }

  inline InstallSnapshotReply& operator=(const InstallSnapshotReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline InstallSnapshotReply& operator=(InstallSnapshotReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InstallSnapshotReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const InstallSnapshotReply* internal_default_instance() {
    return reinterpret_cast<const InstallSnapshotReply*>(
               &_InstallSnapshotReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(InstallSnapshotReply& a, InstallSnapshotReply& b) {
    a.Swap(&b);
  }
  inline void Swap(InstallSnapshotReply* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InstallSnapshotReply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InstallSnapshotReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<InstallSnapshotReply>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const InstallSnapshotReply& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const InstallSnapshotReply& from) {
    InstallSnapshotReply::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InstallSnapshotReply* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "raftrpc.InstallSnapshotReply";
  }
  protected:
  explicit InstallSnapshotReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTermFieldNumber = 1,
  };
  // int32 term = 1;
  void clear_term();
  int32_t term() const;
  void set_term(int32_t value);
  private:
  int32_t _internal_term() const;
  void _internal_set_term(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:raftrpc.InstallSnapshotReply)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t term_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_raft_5frpc_2eproto;
};
// ===================================================================

class RaftRpcService_Stub;

class RaftRpcService : public ::PROTOBUF_NAMESPACE_ID::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline RaftRpcService() {};
 public:
  virtual ~RaftRpcService();

  typedef RaftRpcService_Stub Stub;

  static const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* descriptor();

  virtual void AppendEntries(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::raftrpc::AppendEntriesArgs* request,
                       ::raftrpc::AppendEntriesReply* response,
                       ::google::protobuf::Closure* done);
  virtual void RequestVote(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::raftrpc::RequestVoteArgs* request,
                       ::raftrpc::RequestVoteReply* response,
                       ::google::protobuf::Closure* done);
  virtual void InstallSnapshot(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::raftrpc::InstallSnapshotArgs* request,
                       ::raftrpc::InstallSnapshotReply* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                  ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                  const ::PROTOBUF_NAMESPACE_ID::Message* request,
                  ::PROTOBUF_NAMESPACE_ID::Message* response,
                  ::google::protobuf::Closure* done);
  const ::PROTOBUF_NAMESPACE_ID::Message& GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;
  const ::PROTOBUF_NAMESPACE_ID::Message& GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(RaftRpcService);
};

class RaftRpcService_Stub : public RaftRpcService {
 public:
  RaftRpcService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel);
  RaftRpcService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
                   ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership);
  ~RaftRpcService_Stub();

  inline ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel() { return channel_; }

  // implements RaftRpcService ------------------------------------------

  void AppendEntries(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::raftrpc::AppendEntriesArgs* request,
                       ::raftrpc::AppendEntriesReply* response,
                       ::google::protobuf::Closure* done);
  void RequestVote(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::raftrpc::RequestVoteArgs* request,
                       ::raftrpc::RequestVoteReply* response,
                       ::google::protobuf::Closure* done);
  void InstallSnapshot(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::raftrpc::InstallSnapshotArgs* request,
                       ::raftrpc::InstallSnapshotReply* response,
                       ::google::protobuf::Closure* done);
 private:
  ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(RaftRpcService_Stub);
};


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LogEntry

// bytes command = 1;
inline void LogEntry::clear_command() {
  _impl_.command_.ClearToEmpty();
}
inline const std::string& LogEntry::command() const {
  // @@protoc_insertion_point(field_get:raftrpc.LogEntry.command)
  return _internal_command();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LogEntry::set_command(ArgT0&& arg0, ArgT... args) {
 
 _impl_.command_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:raftrpc.LogEntry.command)
}
inline std::string* LogEntry::mutable_command() {
  std::string* _s = _internal_mutable_command();
  // @@protoc_insertion_point(field_mutable:raftrpc.LogEntry.command)
  return _s;
}
inline const std::string& LogEntry::_internal_command() const {
  return _impl_.command_.Get();
}
inline void LogEntry::_internal_set_command(const std::string& value) {
  
  _impl_.command_.Set(value, GetArenaForAllocation());
}
inline std::string* LogEntry::_internal_mutable_command() {
  
  return _impl_.command_.Mutable(GetArenaForAllocation());
}
inline std::string* LogEntry::release_command() {
  // @@protoc_insertion_point(field_release:raftrpc.LogEntry.command)
  return _impl_.command_.Release();
}
inline void LogEntry::set_allocated_command(std::string* command) {
  if (command != nullptr) {
    
  } else {
    
  }
  _impl_.command_.SetAllocated(command, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.command_.IsDefault()) {
    _impl_.command_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:raftrpc.LogEntry.command)
}

// int32 log_term = 2;
inline void LogEntry::clear_log_term() {
  _impl_.log_term_ = 0;
}
inline int32_t LogEntry::_internal_log_term() const {
  return _impl_.log_term_;
}
inline int32_t LogEntry::log_term() const {
  // @@protoc_insertion_point(field_get:raftrpc.LogEntry.log_term)
  return _internal_log_term();
}
inline void LogEntry::_internal_set_log_term(int32_t value) {
  
  _impl_.log_term_ = value;
}
inline void LogEntry::set_log_term(int32_t value) {
  _internal_set_log_term(value);
  // @@protoc_insertion_point(field_set:raftrpc.LogEntry.log_term)
}

// int32 log_index = 3;
inline void LogEntry::clear_log_index() {
  _impl_.log_index_ = 0;
}
inline int32_t LogEntry::_internal_log_index() const {
  return _impl_.log_index_;
}
inline int32_t LogEntry::log_index() const {
  // @@protoc_insertion_point(field_get:raftrpc.LogEntry.log_index)
  return _internal_log_index();
}
inline void LogEntry::_internal_set_log_index(int32_t value) {
  
  _impl_.log_index_ = value;
}
inline void LogEntry::set_log_index(int32_t value) {
  _internal_set_log_index(value);
  // @@protoc_insertion_point(field_set:raftrpc.LogEntry.log_index)
}

// -------------------------------------------------------------------

// AppendEntriesArgs

// int32 term = 1;
inline void AppendEntriesArgs::clear_term() {
  _impl_.term_ = 0;
}
inline int32_t AppendEntriesArgs::_internal_term() const {
  return _impl_.term_;
}
inline int32_t AppendEntriesArgs::term() const {
  // @@protoc_insertion_point(field_get:raftrpc.AppendEntriesArgs.term)
  return _internal_term();
}
inline void AppendEntriesArgs::_internal_set_term(int32_t value) {
  
  _impl_.term_ = value;
}
inline void AppendEntriesArgs::set_term(int32_t value) {
  _internal_set_term(value);
  // @@protoc_insertion_point(field_set:raftrpc.AppendEntriesArgs.term)
}

// int32 leader_id = 2;
inline void AppendEntriesArgs::clear_leader_id() {
  _impl_.leader_id_ = 0;
}
inline int32_t AppendEntriesArgs::_internal_leader_id() const {
  return _impl_.leader_id_;
}
inline int32_t AppendEntriesArgs::leader_id() const {
  // @@protoc_insertion_point(field_get:raftrpc.AppendEntriesArgs.leader_id)
  return _internal_leader_id();
}
inline void AppendEntriesArgs::_internal_set_leader_id(int32_t value) {
  
  _impl_.leader_id_ = value;
}
inline void AppendEntriesArgs::set_leader_id(int32_t value) {
  _internal_set_leader_id(value);
  // @@protoc_insertion_point(field_set:raftrpc.AppendEntriesArgs.leader_id)
}

// int32 leader_commit = 3;
inline void AppendEntriesArgs::clear_leader_commit() {
  _impl_.leader_commit_ = 0;
}
inline int32_t AppendEntriesArgs::_internal_leader_commit() const {
  return _impl_.leader_commit_;
}
inline int32_t AppendEntriesArgs::leader_commit() const {
  // @@protoc_insertion_point(field_get:raftrpc.AppendEntriesArgs.leader_commit)
  return _internal_leader_commit();
}
inline void AppendEntriesArgs::_internal_set_leader_commit(int32_t value) {
  
  _impl_.leader_commit_ = value;
}
inline void AppendEntriesArgs::set_leader_commit(int32_t value) {
  _internal_set_leader_commit(value);
  // @@protoc_insertion_point(field_set:raftrpc.AppendEntriesArgs.leader_commit)
}

// int32 prev_log_term = 4;
inline void AppendEntriesArgs::clear_prev_log_term() {
  _impl_.prev_log_term_ = 0;
}
inline int32_t AppendEntriesArgs::_internal_prev_log_term() const {
  return _impl_.prev_log_term_;
}
inline int32_t AppendEntriesArgs::prev_log_term() const {
  // @@protoc_insertion_point(field_get:raftrpc.AppendEntriesArgs.prev_log_term)
  return _internal_prev_log_term();
}
inline void AppendEntriesArgs::_internal_set_prev_log_term(int32_t value) {
  
  _impl_.prev_log_term_ = value;
}
inline void AppendEntriesArgs::set_prev_log_term(int32_t value) {
  _internal_set_prev_log_term(value);
  // @@protoc_insertion_point(field_set:raftrpc.AppendEntriesArgs.prev_log_term)
}

// int32 prev_log_index = 5;
inline void AppendEntriesArgs::clear_prev_log_index() {
  _impl_.prev_log_index_ = 0;
}
inline int32_t AppendEntriesArgs::_internal_prev_log_index() const {
  return _impl_.prev_log_index_;
}
inline int32_t AppendEntriesArgs::prev_log_index() const {
  // @@protoc_insertion_point(field_get:raftrpc.AppendEntriesArgs.prev_log_index)
  return _internal_prev_log_index();
}
inline void AppendEntriesArgs::_internal_set_prev_log_index(int32_t value) {
  
  _impl_.prev_log_index_ = value;
}
inline void AppendEntriesArgs::set_prev_log_index(int32_t value) {
  _internal_set_prev_log_index(value);
  // @@protoc_insertion_point(field_set:raftrpc.AppendEntriesArgs.prev_log_index)
}

// repeated .raftrpc.LogEntry log_entries = 6;
inline int AppendEntriesArgs::_internal_log_entries_size() const {
  return _impl_.log_entries_.size();
}
inline int AppendEntriesArgs::log_entries_size() const {
  return _internal_log_entries_size();
}
inline void AppendEntriesArgs::clear_log_entries() {
  _impl_.log_entries_.Clear();
}
inline ::raftrpc::LogEntry* AppendEntriesArgs::mutable_log_entries(int index) {
  // @@protoc_insertion_point(field_mutable:raftrpc.AppendEntriesArgs.log_entries)
  return _impl_.log_entries_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::raftrpc::LogEntry >*
AppendEntriesArgs::mutable_log_entries() {
  // @@protoc_insertion_point(field_mutable_list:raftrpc.AppendEntriesArgs.log_entries)
  return &_impl_.log_entries_;
}
inline const ::raftrpc::LogEntry& AppendEntriesArgs::_internal_log_entries(int index) const {
  return _impl_.log_entries_.Get(index);
}
inline const ::raftrpc::LogEntry& AppendEntriesArgs::log_entries(int index) const {
  // @@protoc_insertion_point(field_get:raftrpc.AppendEntriesArgs.log_entries)
  return _internal_log_entries(index);
}
inline ::raftrpc::LogEntry* AppendEntriesArgs::_internal_add_log_entries() {
  return _impl_.log_entries_.Add();
}
inline ::raftrpc::LogEntry* AppendEntriesArgs::add_log_entries() {
  ::raftrpc::LogEntry* _add = _internal_add_log_entries();
  // @@protoc_insertion_point(field_add:raftrpc.AppendEntriesArgs.log_entries)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::raftrpc::LogEntry >&
AppendEntriesArgs::log_entries() const {
  // @@protoc_insertion_point(field_list:raftrpc.AppendEntriesArgs.log_entries)
  return _impl_.log_entries_;
}

// -------------------------------------------------------------------

// AppendEntriesReply

// int32 term = 1;
inline void AppendEntriesReply::clear_term() {
  _impl_.term_ = 0;
}
inline int32_t AppendEntriesReply::_internal_term() const {
  return _impl_.term_;
}
inline int32_t AppendEntriesReply::term() const {
  // @@protoc_insertion_point(field_get:raftrpc.AppendEntriesReply.term)
  return _internal_term();
}
inline void AppendEntriesReply::_internal_set_term(int32_t value) {
  
  _impl_.term_ = value;
}
inline void AppendEntriesReply::set_term(int32_t value) {
  _internal_set_term(value);
  // @@protoc_insertion_point(field_set:raftrpc.AppendEntriesReply.term)
}

// bool success = 2;
inline void AppendEntriesReply::clear_success() {
  _impl_.success_ = false;
}
inline bool AppendEntriesReply::_internal_success() const {
  return _impl_.success_;
}
inline bool AppendEntriesReply::success() const {
  // @@protoc_insertion_point(field_get:raftrpc.AppendEntriesReply.success)
  return _internal_success();
}
inline void AppendEntriesReply::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void AppendEntriesReply::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:raftrpc.AppendEntriesReply.success)
}

// int32 next_update_index = 3;
inline void AppendEntriesReply::clear_next_update_index() {
  _impl_.next_update_index_ = 0;
}
inline int32_t AppendEntriesReply::_internal_next_update_index() const {
  return _impl_.next_update_index_;
}
inline int32_t AppendEntriesReply::next_update_index() const {
  // @@protoc_insertion_point(field_get:raftrpc.AppendEntriesReply.next_update_index)
  return _internal_next_update_index();
}
inline void AppendEntriesReply::_internal_set_next_update_index(int32_t value) {
  
  _impl_.next_update_index_ = value;
}
inline void AppendEntriesReply::set_next_update_index(int32_t value) {
  _internal_set_next_update_index(value);
  // @@protoc_insertion_point(field_set:raftrpc.AppendEntriesReply.next_update_index)
}

// int32 raft_state = 4;
inline void AppendEntriesReply::clear_raft_state() {
  _impl_.raft_state_ = 0;
}
inline int32_t AppendEntriesReply::_internal_raft_state() const {
  return _impl_.raft_state_;
}
inline int32_t AppendEntriesReply::raft_state() const {
  // @@protoc_insertion_point(field_get:raftrpc.AppendEntriesReply.raft_state)
  return _internal_raft_state();
}
inline void AppendEntriesReply::_internal_set_raft_state(int32_t value) {
  
  _impl_.raft_state_ = value;
}
inline void AppendEntriesReply::set_raft_state(int32_t value) {
  _internal_set_raft_state(value);
  // @@protoc_insertion_point(field_set:raftrpc.AppendEntriesReply.raft_state)
}

// -------------------------------------------------------------------

// RequestVoteArgs

// int32 term = 1;
inline void RequestVoteArgs::clear_term() {
  _impl_.term_ = 0;
}
inline int32_t RequestVoteArgs::_internal_term() const {
  return _impl_.term_;
}
inline int32_t RequestVoteArgs::term() const {
  // @@protoc_insertion_point(field_get:raftrpc.RequestVoteArgs.term)
  return _internal_term();
}
inline void RequestVoteArgs::_internal_set_term(int32_t value) {
  
  _impl_.term_ = value;
}
inline void RequestVoteArgs::set_term(int32_t value) {
  _internal_set_term(value);
  // @@protoc_insertion_point(field_set:raftrpc.RequestVoteArgs.term)
}

// int32 candidate_id = 2;
inline void RequestVoteArgs::clear_candidate_id() {
  _impl_.candidate_id_ = 0;
}
inline int32_t RequestVoteArgs::_internal_candidate_id() const {
  return _impl_.candidate_id_;
}
inline int32_t RequestVoteArgs::candidate_id() const {
  // @@protoc_insertion_point(field_get:raftrpc.RequestVoteArgs.candidate_id)
  return _internal_candidate_id();
}
inline void RequestVoteArgs::_internal_set_candidate_id(int32_t value) {
  
  _impl_.candidate_id_ = value;
}
inline void RequestVoteArgs::set_candidate_id(int32_t value) {
  _internal_set_candidate_id(value);
  // @@protoc_insertion_point(field_set:raftrpc.RequestVoteArgs.candidate_id)
}

// int32 last_log_term = 3;
inline void RequestVoteArgs::clear_last_log_term() {
  _impl_.last_log_term_ = 0;
}
inline int32_t RequestVoteArgs::_internal_last_log_term() const {
  return _impl_.last_log_term_;
}
inline int32_t RequestVoteArgs::last_log_term() const {
  // @@protoc_insertion_point(field_get:raftrpc.RequestVoteArgs.last_log_term)
  return _internal_last_log_term();
}
inline void RequestVoteArgs::_internal_set_last_log_term(int32_t value) {
  
  _impl_.last_log_term_ = value;
}
inline void RequestVoteArgs::set_last_log_term(int32_t value) {
  _internal_set_last_log_term(value);
  // @@protoc_insertion_point(field_set:raftrpc.RequestVoteArgs.last_log_term)
}

// int32 last_log_index = 4;
inline void RequestVoteArgs::clear_last_log_index() {
  _impl_.last_log_index_ = 0;
}
inline int32_t RequestVoteArgs::_internal_last_log_index() const {
  return _impl_.last_log_index_;
}
inline int32_t RequestVoteArgs::last_log_index() const {
  // @@protoc_insertion_point(field_get:raftrpc.RequestVoteArgs.last_log_index)
  return _internal_last_log_index();
}
inline void RequestVoteArgs::_internal_set_last_log_index(int32_t value) {
  
  _impl_.last_log_index_ = value;
}
inline void RequestVoteArgs::set_last_log_index(int32_t value) {
  _internal_set_last_log_index(value);
  // @@protoc_insertion_point(field_set:raftrpc.RequestVoteArgs.last_log_index)
}

// -------------------------------------------------------------------

// RequestVoteReply

// int32 term = 1;
inline void RequestVoteReply::clear_term() {
  _impl_.term_ = 0;
}
inline int32_t RequestVoteReply::_internal_term() const {
  return _impl_.term_;
}
inline int32_t RequestVoteReply::term() const {
  // @@protoc_insertion_point(field_get:raftrpc.RequestVoteReply.term)
  return _internal_term();
}
inline void RequestVoteReply::_internal_set_term(int32_t value) {
  
  _impl_.term_ = value;
}
inline void RequestVoteReply::set_term(int32_t value) {
  _internal_set_term(value);
  // @@protoc_insertion_point(field_set:raftrpc.RequestVoteReply.term)
}

// bool vote_granted = 2;
inline void RequestVoteReply::clear_vote_granted() {
  _impl_.vote_granted_ = false;
}
inline bool RequestVoteReply::_internal_vote_granted() const {
  return _impl_.vote_granted_;
}
inline bool RequestVoteReply::vote_granted() const {
  // @@protoc_insertion_point(field_get:raftrpc.RequestVoteReply.vote_granted)
  return _internal_vote_granted();
}
inline void RequestVoteReply::_internal_set_vote_granted(bool value) {
  
  _impl_.vote_granted_ = value;
}
inline void RequestVoteReply::set_vote_granted(bool value) {
  _internal_set_vote_granted(value);
  // @@protoc_insertion_point(field_set:raftrpc.RequestVoteReply.vote_granted)
}

// int32 vote_state = 3;
inline void RequestVoteReply::clear_vote_state() {
  _impl_.vote_state_ = 0;
}
inline int32_t RequestVoteReply::_internal_vote_state() const {
  return _impl_.vote_state_;
}
inline int32_t RequestVoteReply::vote_state() const {
  // @@protoc_insertion_point(field_get:raftrpc.RequestVoteReply.vote_state)
  return _internal_vote_state();
}
inline void RequestVoteReply::_internal_set_vote_state(int32_t value) {
  
  _impl_.vote_state_ = value;
}
inline void RequestVoteReply::set_vote_state(int32_t value) {
  _internal_set_vote_state(value);
  // @@protoc_insertion_point(field_set:raftrpc.RequestVoteReply.vote_state)
}

// -------------------------------------------------------------------

// InstallSnapshotArgs

// int32 term = 1;
inline void InstallSnapshotArgs::clear_term() {
  _impl_.term_ = 0;
}
inline int32_t InstallSnapshotArgs::_internal_term() const {
  return _impl_.term_;
}
inline int32_t InstallSnapshotArgs::term() const {
  // @@protoc_insertion_point(field_get:raftrpc.InstallSnapshotArgs.term)
  return _internal_term();
}
inline void InstallSnapshotArgs::_internal_set_term(int32_t value) {
  
  _impl_.term_ = value;
}
inline void InstallSnapshotArgs::set_term(int32_t value) {
  _internal_set_term(value);
  // @@protoc_insertion_point(field_set:raftrpc.InstallSnapshotArgs.term)
}

// int32 leader_id = 2;
inline void InstallSnapshotArgs::clear_leader_id() {
  _impl_.leader_id_ = 0;
}
inline int32_t InstallSnapshotArgs::_internal_leader_id() const {
  return _impl_.leader_id_;
}
inline int32_t InstallSnapshotArgs::leader_id() const {
  // @@protoc_insertion_point(field_get:raftrpc.InstallSnapshotArgs.leader_id)
  return _internal_leader_id();
}
inline void InstallSnapshotArgs::_internal_set_leader_id(int32_t value) {
  
  _impl_.leader_id_ = value;
}
inline void InstallSnapshotArgs::set_leader_id(int32_t value) {
  _internal_set_leader_id(value);
  // @@protoc_insertion_point(field_set:raftrpc.InstallSnapshotArgs.leader_id)
}

// int32 last_snapshot_term = 3;
inline void InstallSnapshotArgs::clear_last_snapshot_term() {
  _impl_.last_snapshot_term_ = 0;
}
inline int32_t InstallSnapshotArgs::_internal_last_snapshot_term() const {
  return _impl_.last_snapshot_term_;
}
inline int32_t InstallSnapshotArgs::last_snapshot_term() const {
  // @@protoc_insertion_point(field_get:raftrpc.InstallSnapshotArgs.last_snapshot_term)
  return _internal_last_snapshot_term();
}
inline void InstallSnapshotArgs::_internal_set_last_snapshot_term(int32_t value) {
  
  _impl_.last_snapshot_term_ = value;
}
inline void InstallSnapshotArgs::set_last_snapshot_term(int32_t value) {
  _internal_set_last_snapshot_term(value);
  // @@protoc_insertion_point(field_set:raftrpc.InstallSnapshotArgs.last_snapshot_term)
}

// int32 last_snapshot_index = 4;
inline void InstallSnapshotArgs::clear_last_snapshot_index() {
  _impl_.last_snapshot_index_ = 0;
}
inline int32_t InstallSnapshotArgs::_internal_last_snapshot_index() const {
  return _impl_.last_snapshot_index_;
}
inline int32_t InstallSnapshotArgs::last_snapshot_index() const {
  // @@protoc_insertion_point(field_get:raftrpc.InstallSnapshotArgs.last_snapshot_index)
  return _internal_last_snapshot_index();
}
inline void InstallSnapshotArgs::_internal_set_last_snapshot_index(int32_t value) {
  
  _impl_.last_snapshot_index_ = value;
}
inline void InstallSnapshotArgs::set_last_snapshot_index(int32_t value) {
  _internal_set_last_snapshot_index(value);
  // @@protoc_insertion_point(field_set:raftrpc.InstallSnapshotArgs.last_snapshot_index)
}

// bytes data = 5;
inline void InstallSnapshotArgs::clear_data() {
  _impl_.data_.ClearToEmpty();
}
inline const std::string& InstallSnapshotArgs::data() const {
  // @@protoc_insertion_point(field_get:raftrpc.InstallSnapshotArgs.data)
  return _internal_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void InstallSnapshotArgs::set_data(ArgT0&& arg0, ArgT... args) {
 
 _impl_.data_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:raftrpc.InstallSnapshotArgs.data)
}
inline std::string* InstallSnapshotArgs::mutable_data() {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:raftrpc.InstallSnapshotArgs.data)
  return _s;
}
inline const std::string& InstallSnapshotArgs::_internal_data() const {
  return _impl_.data_.Get();
}
inline void InstallSnapshotArgs::_internal_set_data(const std::string& value) {
  
  _impl_.data_.Set(value, GetArenaForAllocation());
}
inline std::string* InstallSnapshotArgs::_internal_mutable_data() {
  
  return _impl_.data_.Mutable(GetArenaForAllocation());
}
inline std::string* InstallSnapshotArgs::release_data() {
  // @@protoc_insertion_point(field_release:raftrpc.InstallSnapshotArgs.data)
  return _impl_.data_.Release();
}
inline void InstallSnapshotArgs::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  _impl_.data_.SetAllocated(data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:raftrpc.InstallSnapshotArgs.data)
}

// -------------------------------------------------------------------

// InstallSnapshotReply

// int32 term = 1;
inline void InstallSnapshotReply::clear_term() {
  _impl_.term_ = 0;
}
inline int32_t InstallSnapshotReply::_internal_term() const {
  return _impl_.term_;
}
inline int32_t InstallSnapshotReply::term() const {
  // @@protoc_insertion_point(field_get:raftrpc.InstallSnapshotReply.term)
  return _internal_term();
}
inline void InstallSnapshotReply::_internal_set_term(int32_t value) {
  
  _impl_.term_ = value;
}
inline void InstallSnapshotReply::set_term(int32_t value) {
  _internal_set_term(value);
  // @@protoc_insertion_point(field_set:raftrpc.InstallSnapshotReply.term)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace raftrpc

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_raft_5frpc_2eproto
